name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Streamlit app
        run: curl -s https://mediscopeai.streamlit.app > /dev/null
